### ISSUE TITLE
DateTime.Parse vs DateTime.ParaseExact

### ISSUE THREAD

**Issue by wangzhengguang** [edgeofsanity76/LeetU#1]
Line 30 of EntityToModel caused this exception:  System.FormatException: 'String '23/12/1982' was not recognized as a valid DateTime.', when it tried to map the DateOfBirth from Entity to the Model.

To resolve the exception, use DateTime.ParseExact with three parameters, instead of DateTime.Parse.
    student.DateOfBirth = DateTime.ParseExact(entity.DateOfBirth,"dd/MM/yyyy" ,CultureInfo.InvariantCulture);

**Comment by edgeofsanity76** [comment]
Thank you. This has been fixed
